import { Router } from "express";
import handlerPatient from "../../handler/patient.handler";
import handlerBans from "~~/handler/ban.handler";
import handlerConge from "~~/handler/conge.handler";
import handlerLocalisation from "~~/handler/localisation.handler";
import handlerPraticien from "~~/handler/praticien.handler";
import handlerPlageHoraire from "~~/handler/plage_horaire.handler";
import handlerPlanning from "~~/handler/planning.handler";
import handlerRdv from "~~/handler/rdv.handler";
import handlerRole from "~~/handler/role.handler";
import handlerToken from "~~/handler/token.handler";
import handlerUser from "~~/handler/user.handler";
export const router = Router();

router.get('/patient', handlerPatient.getPatients);
router.get('/bans', handlerBans.getBans);
router.get('/conges', handlerConge.getConges);
router.get('/localisation', handlerLocalisation.getLocalisation);
router.get('/praticiens', handlerPraticien.getPraticien);
router.get('/plagehoraires', handlerPlageHoraire.getPlageHoraire);
router.get('/planning', handlerPlanning.getPlanning);
router.get('/rdvs', handlerRdv.getRdv);
router.get('/roles', handlerRole.getRole);
router.get('/tokens', handlerToken.getToken);
router.get('/users', handlerUser.getUser);